version: '3.3'

services:
  springboot:
    image: ghcr.io/unirun/unirun-api-server:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: unirun-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=unirun
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ~/docker/mariadb/etc/mysql/conf.d/etc/mysql/conf.d:ro
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysqql
      - ~/docker/mariadb/var/log/mariadb:/var/log/mariadb
    networks:
      - backend

networks:
  backend: